sudo: false

language: node_js

matrix:
  include:
    - node_js: 'node'
      env: NPM_RUN_SCRIPT=test
    - node_js: '10'
    - node_js: '8'
    - node_js: '6'

install:
  - npm install

script:
  - npm run ${NPM_RUN_SCRIPT:-test:spec}
